# Generated by Django 4.2.7 on 2024-01-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
