# Generated by Django 4.2.7 on 2024-01-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDB', '0002_alter_image_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
    ]
